version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cs301
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  backend:
    build: .
    container_name: backend-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=mysql  # Automatically linked to mysql service
    depends_on:
      - mysql
    restart: always

volumes:
  mysql-data:
